version: '3.8'

services:
  botvang:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1000
    container_name: gold-price-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/home/appuser/.env
    # For improved security
    security_opt:
      - no-new-privileges:true
    # Healthcheck to ensure the application is running properly
    healthcheck:
      test: ["CMD", "python", "-c", "import os, sys; sys.exit(0 if os.path.exists('/home/appuser/.env') else 1)"]
      interval: 1m
      timeout: 10s
      retries: 3
